program: msa
project: "sms_service"
projectCode: code
data: ""
method: GET
namespace: pxsj
metrics:
 - http_code
 - program_code
header:
  Content-Type: "application/json"
  Accept: "application/json"
url: "/v1/sms/template.get"
host: "sms-service"
port: "8301"
protocol: "http"
