program: msa
project: "sms_service"
projectCode: code
env: swarm
data: ""
method: GET
metrics:
 - http_code
 - program_code
header:
  Content-Type: "application/json"
  Accept: "application/json"
url: "/v1/fff/ccc"
host: "sms-service"
port: "8301"
protocol: "http"
